services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true
