services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
      - ENV=${ENV}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true
